#!/bin/bash
docker compose -f ./docker-compose.yml -f ./docker-compose.override.yml --env-file ./.env down
docker network create chat-network
sudo docker compose -f ./devlocal/docker-compose.yml -f ./devlocal/docker-compose.override.yml --env-file ./.env down
sudo docker compose -f ./devlocal/docker-compose.yml -f ./devlocal/docker-compose.override.yml --env-file ./.env up -d
npm run backend:dev